### PR TITLE
Better verbose on js code

### PR DESCRIPTION
**Pull request by jfoclpf**
this is just an initial PR, I will update then the hooks for iOS

### CODE REVIEW

**Review by ChrisTomAlx — COMMENTED** [review]
Looks Good to me so far. Are you done with all the changes ?

**Comment by jfoclpf** [comment]
yes, for now, yes. I wanted to automate in iOS but as you correctly pointed out it's something to do with the project itself, which again is strange, because this is the only plugin that demands pod install :)

**Comment by jfoclpf** [comment]
Hi @ChrisTomAlx don't forget to merge this PR :)

**Comment by ChrisTomAlx** [comment]
Sorry don't want to remove iOS support completely. You may fork and use it that way for now.

**Pull request closed without merging**
